import Link from "next/link";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import "@fontsource/amiko";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="m-3">{children}</main>
      <Footer />
    </>
  );
}
