import Link from "next/link";
import Head from "next/head";
import Footer from "./footer";
import Header from "./header";
import "@fontsource/amiko";
import { ReactElement, ReactNode } from "react";

type Props = {
  children: ReactNode;
};

const Layout = (props: Props) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.3.2/build/styles/default.min.css"
        ></link>
        <title>yorn.dev</title>
      </Head>
      <Header />
      <main className="m-3 w-full flex flex-row justify-center">
        <div className="w-full md:w-2/3 lg:w-1/3">{props.children}</div>
      </main>
      <Footer />
    </>
  );
};

export default Layout;
