import Link from "next/link";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import "@fontsource/amiko";
import { ReactElement, ReactNode } from "react";

type Props = {
  children: ReactNode;
};

const Layout = (props: Props) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>yorn.dev</title>
      </Head>
      <Header />
      <main className="m-3">{props.children}</main>
      <Footer />
    </>
  );
};

export default Layout;
